plugin := "./sample.esp"

# spriggit := "Spriggit.CLI"
spriggit := "/tmp/Spriggit/CLIs/0.34.0/Spriggit.CLI.exe"

spriggit_output := "./plugins"

test-serialize:
    {{ spriggit }} serialize \
        -i {{ plugin }} \
        -o {{ spriggit_output }}/$(basename {{ plugin }}) \
        -g SkyrimSE \
        -p Spriggit.Yaml.Skyrim
